# Generated by Django 2.2.17 on 2020-11-11 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('doc', models.CharField(blank=True, max_length=14, null=True, verbose_name='Doc')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Phone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('type_person', models.CharField(choices=[('1', 'Person'), ('2', 'Company')], default='1', max_length=1, verbose_name='Type of Person')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Produto')),
                ('price', models.FloatField(verbose_name='Price')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Weight')),
                ('type_product', models.CharField(choices=[('1', 'Product'), ('2', 'Service')], default='1', max_length=1, verbose_name='Type of Product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateField(auto_now_add=True, verbose_name='Order Date')),
                ('total_value', models.FloatField(blank=True, null=True, verbose_name='Total Value')),
                ('type_of_payment', models.CharField(choices=[('1', 'Cash'), ('2', 'Credit Card'), ('3', 'Mobile payments'), ('4', 'Bank Transfer')], default='1', max_length=1, verbose_name='Type of Payment')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_main.Client', verbose_name='Client')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SaleOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1, verbose_name='Quantity')),
                ('discount', models.FloatField(default=0.0, verbose_name='Discount')),
                ('total_value', models.FloatField(blank=True, null=True, verbose_name='Total Value')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_main.SaleOrder', verbose_name='Order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_main.Product', verbose_name='Product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
